# specify the name of your project
name: Nextjs-CICD

# Configure what events and branches you want to trigger your pipeline on, in this case I want it to be trgiggered when I push the code in react-profile branch
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
    
# Create jobs to create your image which you can deploy on AWS, I am running my Node14 application on amazon linux 2. 
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Beanstalk Deploy for app
      uses: hmanzur/actions-aws-eb@v1.0.0
      with:
        command: 'deploy ${{ secrets.ENVIRONMENT_NAME }}'
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_DEFAULT_REGION: "us-east-1"

